name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
      release_name:
        description: 'Release name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'

    - name: Build and Release
      run: |
        make all
        # You can add any additional steps here, such as testing or other actions you need before releasing

    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/*
        tag_name: ${{ github.event.inputs.tag_name }}
        name: ${{ github.event.inputs.release_name }}
        draft: false
        token: ${{ secrets.RELEASE_TOKEN }}
